config/routes.rb
Rails.application.routes.draw do
  resources :viajes
  root 'stuv#index'

  get        '/perfil', to: 'users#show', as: :perfil
  get        '/signup', to: 'users#new', as: :new_user
  get '/editar_perfil', to: 'users#edit', as: :edit_user
  get         '/login', to: 'sessions#new'
  post        '/login', to: 'sessions#create'
  delete     '/logout', to: 'sessions#destroy'

  resources :users, except: [:show, :new, :edit]
  resources :vehicles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :foto, ImageUploader
  has_one :vehicle
  has_one :viaje

  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :nombre, :apellido_paterno, :apellido_materno, :foto, :telefono, presence: true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  mount_uploader :foto, ImageUploader
  belongs_to :user
end

app/models/viaje.rb
class Viaje < ApplicationRecord
  belongs_to :user
  belongs_to :place
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(id: params[:session][:id], password: params[:session][:password])
    if user
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      redirect_to root_path
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/stuv_controller.rb
class StuvController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to '/perfil', notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    log_out
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_user
      @user = User.find(current_user.id)
    end

    def user_params
      params.require(:user).permit(:id, :password, :password_confirmation, :nombre, :apellido_paterno, :apellido_materno, :foto, :telefono)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  
  def show
    @vehicle = Vehicle.find(params[:id])
  end

  def new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user_id = current_user.id
    if @vehicle.save
      redirect_to perfil_path
    else
      redirect_to perfil_path
    end
  end

  def destroy
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.destroy
      redirect_to perfil_path
    else
      redirect_to perfil_path
    end
  end

  private

    def vehicle_params
      params.require(:vehicle).permit(:model, :color, :foto)
    end
end

app/controllers/viajes_controller.rb
class ViajesController < ApplicationController
  
  def index
    if params[:p]
      @viajes = Viaje.where(place_id: params[:p])
    end
  end

  def show
    @viaje = Viaje.find(params[:id])
  end

  def new
  end

  def create
    @viaje = Viaje.new(viaje_params)
    @viaje.user_id = current_user.id

    if @viaje.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def destroy
    @viaje = Viaje.find(params[:id])
    if @viaje.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def viaje_params
    params.require(:viaje).permit(:place_id, :time_limit, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "STUV"
    if page_title.empty?
      base_title
    else
      base_title + " | " + page_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/stuv_helper.rb
module StuvHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/viajes_helper.rb
module ViajesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render "navbars/navbar" %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/navbars/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark" style="background: #154D23;">
  <a class="navbar-brand" href="<%= root_path %>">STUV</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <div class="btn-group">
          <% if logged_in?%>
            <%= link_to "Mi perfil", perfil_path, class: "btn text-light", style: "background: #958419;" %>
            <%= link_to "Cerrar sesión", logout_path, method: :delete, class: "btn btn-danger" %>
          <% else %>
            <a href="<%= new_user_path %>" class="btn text-light" style="background: #958419;">Crear cuenta</a>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/stuv/_user_index.html.erb
<% if current_user.viaje %>
  <p class="lead text-center">Has publicado un viaje</p>
  <div class="text-center">
    <div class="display-4 text-center"><%= current_user.viaje.time_limit.strftime('%I:%M %p') %></div><br>
    <div class="font-weight-bold">Lugar de partida:</div> <%= current_user.viaje.place.name %><br>
    <div class="font-weight-bold">Descripción:</div> <%= current_user.viaje.description %>
  </div>
  <%= link_to "Cancelar", viaje_path(current_user.viaje), method: :delete, class: "btn btn-block btn-danger" %>
<% else %>
  <a href="<%= viajes_path %>" class="btn btn-block btn-lg text-light" style="background: #958419;">Pedir viaje</a>
  <a href="<%= new_viaje_path %>" class="btn btn-block btn-lg text-light" style="background: #154D23;">Ofrecer viaje</a>
<% end %>

app/views/stuv/index.html.erb
<% provide(:title, "Inicio") %>
<div class="row ">
  <div class="col-sm-12">
    <div class="jumbotron-fluid text-center">
      <h1 class="display-2">STUV</h1>
      <p class="lead">Sistema de Transporte Universitario</p>
    </div>
    <div class="col-sm-12 col-md-4 mx-auto">
      <% if logged_in? %>
        <%= render "stuv/user_index" %>
      <% else %>
        <%= render "sessions/form" %>
        <a href="<%= new_user_path %>" class="btn btn-block text-light" style="background: #154D23;">Crear cuenta</a>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_edit_form.html.erb
<%= form_for(user) do |f| %>
  
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Contraseña", for: :password %>
    <%= f.password_field :password, requred: true, class: "form-control" %>
  </div>

  <div class="form-group">  
    <%= f.label "Repita contraseña", for: :password_confirmation %>
    <%= f.password_field :password_confirmation, requred: true, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label "Teléfono celular", for: :telefono %>
    <%= f.number_field :telefono, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Tu fotografía", for: :foto %>
    <%= f.file_field :foto, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Enviar", class: "btn btn-block text-light form-control", style: "background: #958419;" %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>

  <div class="form-group">
    <%= f.label "Número de cuenta", for: :id %>
    <%= f.number_field :id, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Contraseña", for: :password %>
    <%= f.password_field :password, requred: true, class: "form-control" %>
  </div>

  <div class="form-group">  
    <%= f.label "Repita contraseña", for: :password_confirmation %>
    <%= f.password_field :password_confirmation, requred: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Nombre(s)", for: :nombre %>
    <%= f.text_field :nombre, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Apellido paterno", for: :apellido_paterno %>
    <%= f.text_field :apellido_paterno, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Apellido materno", for: :apellido_materno %>
    <%= f.text_field :apellido_materno, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Teléfono celular", for: :telefono %>
    <%= f.number_field :telefono, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Tu fotografía", for: :foto %>
    <%= f.file_field :foto, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Enviar", class: "btn btn-block text-light form-control", style: "background: #958419;" %>
  </div>

<% end %>

app/views/users/_perfil.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1 class="display-4 text-center">Mi perfil</h1>
    <%= render "users/user", user: current_user %>
  </div>
</div>

app/views/users/_rutas.html.erb
<% if user.rutas.empty? %>
  <p class="lead text-center">Aun no has agregado ninguna ruta</p>
<% elsif !user.vehicle %>
  <p class="lead text-center">No puedes gestionar tus rutas si no tienes un vehículo registrado</p>
  <a href="<%= new_vehicle_path %>" class="btn btn-success btn-block">Añadir vehículo</a>
<% else %>
  <p class="display-4 text-center">Mis rutas</p>
  <div>
    <% user.rutas.find_each do |ruta| %>
      <%= render "rutas/ruta", ruta: ruta %>
    <% end %>
  </div>
  <a href="<%= new_ruta_path %>" class="btn btn-success btn-block">Añadir ruta</a>
<% end %>

app/views/users/_user.html.erb
<img src="<%= user.foto %>" class="img-fluid img-thumbnail rounded-circle mx-auto d-block" style="max-width: 100px; height: auto;">
<div class="lead text-center">
  <p><%= user.nombre %> <%= user.apellido_paterno %> <%= user.apellido_materno %></p>
  <p>Contacto: <%= user.telefono %></p>
  <% if current_user.id == user.id %>
    <a href="<%= edit_user_path(user) %>" class="btn btn-warning btn-block">Editar</a>
  <% end %>
</div>

app/views/users/_vehicles.html.erb
<% unless user.vehicle %>
  <p class="lead text-center">Aun no has agregado ningun vehículo</p>
  <a href="<%= new_vehicle_path %>" class="btn btn-success btn-block">Añadir vehículo</a>
<% else %>
<div class="row mx-auto">
  <div class="col-sm-12">
    <div class="text-center">
      <h1 class="display-4">Mi Vehículo</h1>
    </div>
  </div>
  <div class="col-sm-12">
    <%= render "vehicles/vehicle", vehicle: user.vehicle %>
  </div>
    <%= link_to "Eliminar vehículo", vehicle_path(user.vehicle), method: :delete, class: "btn btn-block btn-danger" %>
</div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Editar perfil") %>
<div class="row ">
  <div class="col-sm-12">
    <h1 class="text-center">Editar perfil</h1>
    </div>
    <div class="col-sm-12">
      <%= render 'users/edit_form', user: @user %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Registro") %>
<div class="row ">
  <div class="col-sm-12">
    <h1 class="text-center">Registro</h1>
    </div>
    <div class="col-sm-12 col-md-4 mx-auto">
      <%= render 'users/form', user: @user %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Mi perfil") %>

<div class="row">
  <div class="col-sm-12 ">
    <ul id="clothing-nav" class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" href="#perfil" id="perfil-tab" role="tab" data-toggle="tab" aria-controls="perfil" aria-expanded="true">Mi perfil</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#vehicles" id="vehicles-tab" role="tab" data-toggle="tab" aria-controls="vehicles" aria-expanded="true">Mi vehículo</a>
      </li>
    </ul>
    <!-- Content Panel -->
    <div id="clothing-nav-content" class="tab-content">
      <div role="tabpanel" class="tab-pane fade show active" id="perfil" aria-labelledby="perfil-tab">
        <%= render 'users/perfil', user: current_user %>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="vehicles" aria-labelledby="vehicles-tab">
        <%= render 'users/vehicles', user: current_user %>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/_form.html.erb
<%= form_for(vehicle) do |f| %>

  <div class="form-group">
    <%= f.label "Modelo", for: :model %>
    <%= f.text_field :model, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Color", for: :color %>
    <%= f.text_field :color, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Fotografía del vehículo", for: :foto %>
    <%= f.file_field :foto, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Enviar", class: "btn btn-block text-light form-control", style: "background: #958419;" %>
  </div>

<% end %>

app/views/vehicles/_vehicle.html.erb
<img src="<%= vehicle.foto %>" class="img-thumbnail mx-auto d-block" style="width: 300px; height: 300px;">
<p class="lead text-center">
  Modelo: <%= vehicle.model %><br>
  Color: <%= vehicle.color %>
</p>

app/views/vehicles/new.html.erb
<% provide(:title, "Nuevo vehículo") %>
<div class="row ">
  <div class="col-sm-12">
    <h1 class="text-center">Registro de vehículo</h1>
    </div>
    <div class="col-sm-12 col-md-4 mx-auto">
      <%= render 'vehicles/form', vehicle: Vehicle.new %>
    </div>
  </div>
</div>

app/views/vehicles/show.html.erb
<% provide(:title, "Mi vehículo") %>
<div class="row mx-auto">
  <div class="col-sm-12">
    <div class="text-center">
      <h1 class="display-4">Mi Vehículo</h1>
    </div>
  </div>
  <div class="col-sm-12">
    <img src="<%= @vehicle.foto %>" class="img-thumbnail mx-auto d-block" style="width: 300px; height: 300px;">
    <p class="lead text-center">
      Modelo: <%= @vehicle.model %><br>
      Color: <%= @vehicle.color %>
    </p>
    <%= link_to "Eliminar vehículo", vehicle_path(@vehicle), method: :delete, class: "btn btn-block btn-danger" %>
  </div>
</div>

app/views/viajes/_form.html.erb
<%= form_for(viaje) do |f| %>

  <div class="form-group">
    <%= f.label "Lugar de partida", for: :place_id %>
    <%= f.collection_select(:place_id, Place.all, :id, :name, {}, { class: 'form-control', required: true }) %>
    <span class="form-text text-muted">Desde donde partirás, con esto los demás usuarios podrán consultar tu viaje</span>
  </div>

  <div class="form-group">
    <%= f.label "Descripción", for: :description %>
    <%= f.text_area :description, required: true, class: "form-control", placeholder: "p.ej. Terminal, Tollocan, Centro, Fac. Medicina, Comonfort, etc." %>
    <span class="form-text text-muted">Por que lugares o calles vas a pasar.</span>
  </div>

  <div class="form-group">
    <%= f.label "Hora de partida", for: :time_limit %>
    <%= f.time_field :time_limit, required: true, class: "form-control" %>
    <span class="form-text text-muted">Hora límite para partir.</span>
  </div>

  <div class="form-group">
    <%= f.submit "Enviar", class: "btn btn-block text-light form-control", style: "background: #958419;" %>
  </div>

<% end %>

app/views/viajes/index.html.erb
<% if !params[:p] %>
<div class="row">
  <div class="col-sm-12">
    <h1 class="text-center">Solicitar viaje</h1>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <form action="/viajes" method="get">
      <div class="form-group">
        <label>Selecciona el lugar de partida</label>
        <select name="p" id="p" class="form-control" required>
          <% Place.all.find_each do |p| %>
            <option value="<%= p.id %>"><%= p.name %></option>
          <% end %>
      </div>
      <div class="form-group">
        <input type="submit" value="Buscar", class="btn text-light btn-block form-control" style="background: #958419;">
      </div>
    </form>
  </div>
</div>
<% elsif !@viajes.empty? %>
  <div class="row">
    <div class="col-sm-12">
      <h1 class="text-center">Viajes disponibles</h1>
      <div class="table-responsive-sm">
        <table class="table table-sm table-bordered table-striped table-hover text-center">
          <thead class="thead-dark">
            <th>Hora de salida</th>
            <th>Descripción</th>
            <th>Opciones</th>
          </thead>
          <tbody>
            <% @viajes.each do |v| %>
              <td><%= v.time_limit.strftime('%I:%M %p') %></td>
              <td><%= v.description %></td>
              <td><a href="<%= viaje_path(v) %>">Ver</a></td>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% else %>
<h3 class="text-center">No hay ningun viaje disponible</h3>
<p class="lead text-center">Inténtalo más tarde.</p>
<% end %>

app/views/viajes/new.html.erb
<% provide(:title, "Agendar viaje") %>
<% if !current_user.vehicle %>
  <p class="lead text-center">No puedes agendar un viaje si no tienes un vehículo registrado</p>
  <a href="<%= new_vehicle_path %>" class="btn btn-success btn-block">Añadir vehículo</a>
<% else %>
  <h1 class="text-center">Agendar nuevo viaje</h1>
  <%= render 'viajes/form', viaje: Viaje.new %>
<% end %>

app/views/viajes/show.html.erb
<% if @viaje %>
  <div class="row">
    <div class="col-sm-12 text-center">
      <p class="lead text-center">
        <div class="display-4 text-center"><%= @viaje.time_limit.strftime('%I:%M %p') %></div><br>
        <div class="font-weight-bold text-center">Lugar de partida:</div><div class="text-center"><%= @viaje.place.name %></div><br>
        <div class="font-weight-bold text-center">Descripción:</div> <%= @viaje.description %>
      </p>
    </div>
    <div class="col-sm-6">
      <h1 class="text-center">Conductor</h1>
      <%= render "users/user", user: @viaje.user %>
    </div>
    <div class="col-sm-6">
      <h1 class="text-center">Vehículo</h1>
      <%= render "vehicles/vehicle", vehicle: @viaje.user.vehicle %>
    </div>
  </div>
<% end %>